### ISSUE TITLE
At Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by chechucastro** [noseglid/atom-build#112]
Hi,

I have an error when I open Atom editor:

Thanks,
Chechu Castro.

[Enter steps to reproduce below:]

1. ... Open Atom
2. ... Error notification panel is opened on the right side of the editor.

**Atom Version**: 1.0.0
**System**: Windows 8
**Thrown From**: [build-systems](https://github.com/klorenz/atom-build-systems) package, v0.5.0

### Stack Trace

Failed to load the build-systems package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (c:\Users\Chechu\.atom\packages\build-systems\lib\build-output.coffee:5:199)
    at c:\Users\Chechu\.atom\packages\build-systems\lib\build-output.coffee:279:5
    at Object.<anonymous> (c:\Users\Chechu\.atom\packages\build-systems\lib\build-output.coffee:479:5)
    at Object.<anonymous> (c:\Users\Chechu\.atom\packages\build-systems\lib\build-output.coffee:486:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\Chechu\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "useReactEditor": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
atom-color-highlight, v3.0.9
build-systems, v0.5.0
color-picker, v2.0.7
css-snippets, v0.8.0
docblockr, v0.7.2
file-icons, v1.5.8
gulp-snippets, v0.6.1
highlight-selected, v0.10.1
jsformat, v0.9.0
linter, v1.0.9
minimap, v4.10.0
minimap-highlight-selected, v4.3.0
project-colorize, v0.2.0
project-manager, v1.15.10
seti-syntax, v0.4.0
seti-ui, v0.7.1
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by noseglid** [comment]
This is the wrong package. You have an error in a package called `build-systems`. This package is named `build`.
