### ISSUE TITLE
Error when building: ENOENT: no such file or directory, lstat '/home/stefan/atom:'

### ISSUE THREAD

**Issue by poidl** [noseglid/atom-build#128]
Hi, I'm using Atom 1.0.2 (after upgrading from 1.0.0. to see if the problem goes away) and installed atom-build for the first time today. I get the following error when I press ctrl-alt-b in a Rust file:

```
Ooops. Something went wrong.
ENOENT: no such file or directory, lstat '/home/stefan/atom:'
Error: ENOENT: no such file or directory, lstat '/home/stefan/atom:'
  at Error (native)
  at fs.lstatSync (fs.js:836:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
  at Object.realpathSync (fs.js:1439:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:243:29)
  at /home/stefan/.atom/packages/build/lib/build.js:147:27
  at baseFindIndex (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:326:11)
  at Function.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3241:23)
  at Object.module.exports.activePath (/home/stefan/.atom/packages/build/lib/build.js:146:16)
  at Object.module.exports.refreshTargets (/home/stefan/.atom/packages/build/lib/build.js:164:21)
  at Object.<anonymous> (/home/stefan/.atom/packages/build/lib/build.js:267:58)
  at Object.tryCatcher (/home/stefan/.atom/packages/build/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/home/stefan/.atom/packages/build/node_modules/bluebird/js/main/promise.js:489:31)
  at Promise._settlePromiseAt (/home/stefan/.atom/packages/build/node_modules/bluebird/js/main/promise.js:565:18)
  at Promise._settlePromiseAtPostResolution (/home/stefan/.atom/packages/build/node_modules/bluebird/js/main/promise.js:244:10)
  at Async._drainQueue (/home/stefan/.atom/packages/build/node_modules/bluebird/js/main/async.js:128:12)
  at Async._drainQueues (/home/stefan/.atom/packages/build/node_modules/bluebird/js/main/async.js:133:10)
  at MutationObserver.Async.drainQueues (/home/stefan/.atom/packages/build/node_modules/bluebird/js/main/async.js:15:14)
```

Is this easy to solve? Thanks a lot for your help! - Stefan

**Comment by noseglid** [comment]
Is this on Windows? For some reason the project path (as reported by `Atom`) is `/home/stefan/atom:` for you, which seems weird. How do you start `Atom` and open a project?

**Comment by poidl** [comment]
Thanks for your reply! 
First off: I just removed ~/.atom, re-installed atom and all the packages, and the problem is gone! So for me this is solved.
Further info in case this helps: I'm on Kubuntu 15.04 running on virtualbox.  I start atom with the KDE panel icon for atom. I'm using the default atom.desktop file located in /usr/share/applications/atom.desktop:

```
stefan@vb:~$ cat /usr/share/applications/atom.desktop 
[Desktop Entry]
Name=Atom
Comment=A hackable text editor for the 21st Century.
GenericName=Text Editor
Exec=/usr/share/atom/atom %U
Icon=atom
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;TextEditor;Development;
MimeType=text/plain;
```

Regards, S

**Comment by noseglid** [comment]
I'm glad that it is working for you. Weird that it occured though. I think it's more likely an issue with atom. The obviously erroneous path (`/home/stefan/atom:`) is reported by the atom via `getProjectPath`. Hopefully it won't return. Closing this out.
