### ISSUE TITLE
Uncaught TypeError: type RegExp expected

### ISSUE THREAD

**Issue by bodocabdd** [noseglid/atom-build#173]
So, i have this project using a custom .atom-build.json, using cake cmd to join coffee files, among other tasks. My problem is, it was working really fine before some atom and atom-build updates. And now, every time I try to build with an error in my code, the package throws this Exception below and I have to restart atom to be able to trigger build again. I would love to help you and fix this, but I lack the time right now. =(

**Steps**
1. A project thats builds coffee with cake.
2. This .atom-build.json:
```JSON
{
    "cmd": "cake",
    "args": ["sbuild"],
    "sh": true,
    "cwd": "{PROJECT_PATH}"
}
```

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.46.0

### Stack Trace

Uncaught TypeError: type RegExp expected

```
At /Users/myuser/.atom/packages/build/node_modules/xregexp/xregexp-all.js:141

TypeError: type RegExp expected
    at copy (/Users/myuser/.atom/packages/build/node_modules/xregexp/xregexp-all.js:141:19)
    at Function.self.exec (/Users/myuser/.atom/packages/build/node_modules/xregexp/xregexp-all.js:504:18)
    at Function.self.forEach (/Users/myuser/.atom/packages/build/node_modules/xregexp/xregexp-all.js:541:30)
    at ErrorMatcher.module.exports.ErrorMatcher._parse (/Users/myuser/.atom/packages/build/lib/error-matcher.js:80:15)
    at ErrorMatcher.module.exports.ErrorMatcher.set (/Users/myuser/.atom/packages/build/lib/error-matcher.js:127:10)
    at Object.<anonymous> (/Users/myuser/.atom/packages/build/lib/build.js:354:31)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:997:16)
    at Socket.<anonymous> (child_process.js:1166:11)
```

### Commands

```
     -0:36.8.0 build:trigger (atom-text-editor.editor.is-focused)
  3x -0:28 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:26.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:26 core:backspace (atom-text-editor.editor.is-focused)
     -0:25.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:25.5.0 core:close (atom-text-editor.editor.is-focused)
     -0:11.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:11.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:10.2.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:09.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.0 build:trigger (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "save-session",
      "sublime-tabs",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "permute",
      "duplicate-line-or-selection",
      "wrap-guide"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "build": {
    "saveOnBuild": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
build, v0.46.0
compare-files, v0.6.2
emmet, v2.3.12
highlight-selected, v0.10.1
jsformat, v0.9.0
language-coffee-script-angular, v2.2.0
linter, v1.5.1
linter-jshint, v1.2.0
linter-php, v1.0.3
monokai, v0.18.0
php-composer-completion, v0.3.4
project-manager, vundefined
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by noseglid** [comment]
I have an idea on what might be causing this, but unable to verify it fully. Did you have `v0.45.0` installed before upgrading?

**Comment by bodocabdd** [comment]
Yep! I upgraded from 0.45.0 to 0.46.0 today, but the error was there before
that. I'm using this package since 0.37.0 and the updates were made version
by version, without skipping. I think this bug started at version 0.42.0 or
0.43.0.

On Wed, Sep 9, 2015 at 5:54 PM Alexander Olsson <notifications@github.com>
wrote:

> I have an idea on what might be causing this, but unable to verify it
> fully. Did you have v0.45.0 installed before upgrading?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/noseglid/atom-build/issues/173#issuecomment-139042798>
> .
>
-- 
*Rafael Galdêncio*

+55 11 5906-9040

Rua Augusta, 2516, Cobertura, Jardim Paulista - São Paulo - SP
CEP 01412-100
www.indigoway.com
