### ISSUE TITLE
Failed to activate the build package

### ISSUE THREAD

**Issue by karneaud** [noseglid/atom-build#181]
[Enter steps to reproduce below:]

1. Updated from 1.0.12 to 1.0.13
2. Run updated software

**Atom Version**: 1.0.13
**System**: Mac OS X 10.10.5
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.46.0

### Stack Trace

Failed to activate the build package

```
At ENOENT: no such file or directory, lstat '/atom:'

Error: ENOENT: no such file or directory, lstat '/atom:'
  at Error (native)
  at fs.lstatSync (fs.js:844:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
  at Object.realpathSync (fs.js:1449:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
  at /Users/kendallarneaud/.atom/packages/build/lib/build.js:154:27
  at baseFindIndex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:326:11)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3241:23)
  at Object.activePath (/Users/kendallarneaud/.atom/packages/build/lib/build.js:153:16)
  at Object.refreshTargets (/Users/kendallarneaud/.atom/packages/build/lib/build.js:171:21)
  at Object.activate (/Users/kendallarneaud/.atom/packages/build/lib/build.js:129:10)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:670:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:82:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/kendallarneaud/Documents/Git",
    "disabledPackages": [
      "browser-refresh-on-save",
      "autosave"
    ]
  },
  "build": {}
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.5.4
build, v0.46.0
command-toolbar, v1.0.12
compare-files, v0.6.2
git-go, v1.0.1
git-log, v0.4.1
jshint, v1.7.0
language-diff, v0.3.1
linter, v1.5.2
linter-csslint, v1.0.5
linter-htmlhint, v0.1.1
linter-sass-lint, v0.1.4
npm, v0.1.0
rest-client, v0.4.0
sass-compiler, v0.4.0
sass-watch, v0.3.1

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Could you try closing atom and restarting it? If that doesn't work, re-install `build`.

**Comment by karneaud** [comment]
yeah that worked

**Comment by photex** [comment]
Update!

For whatever reason, my keymap is always getting opened when I start Atom now and it's causing this issue each time I believe because my keymap is located at `atom://.atom/keymap`.

I have no idea why my keymap started opening on it's own though.

**Comment by photex** [comment]
Another update!

I just noticed the squirrel,updated and restarted atom and I did not get this exception even with the keymap automatically opening. *software is terrible*
