### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

### ISSUE THREAD

**Issue by photex** [noseglid/atom-build#184]
[Enter steps to reproduce below:]

1. install build plugin
2. test the keyboard shortcut

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.46.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/atom:'

```
At ATOM_SHELL_ASAR.js:118

Error: ENOENT: no such file or directory, lstat '/atom:'
  at Error (native)
  at fs.lstatSync (fs.js:844:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
  at Object.realpathSync (fs.js:1449:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
  at /Users/ccollier/.atom/packages/build/lib/build.js:154:27
  at baseFindIndex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:326:11)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3241:23)
  at Object.activePath (/Users/ccollier/.atom/packages/build/lib/build.js:153:16)
  at Object.refreshTargets (/Users/ccollier/.atom/packages/build/lib/build.js:171:21)
  at Object.selectActiveTarget (/Users/ccollier/.atom/packages/build/lib/build.js:242:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -4:19.9.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -4:19.1.0 editor:select-to-end-of-line (atom-text-editor.editor.mini.is-focused)
     -4:11.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:12 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -3:11.4.0 pane:show-next-item (div.settings-view.pane-item)
     -3:10 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -3:01.3.0 pane:show-next-item (div.settings-view.pane-item)
     -2:59.5.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:32.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:27.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:16.1.0 build:trigger (atom-text-editor.editor.is-focused)
     -0:00.5.0 build:select-active-target (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "base-16-ocean-dark-ui-theme",
      "base16-ocean-dark-spacegray"
    ]
  },
  "build": {
    "saveOnBuild": true
  }
}
```

### Installed Packages

```coffee
# User
base-16-ocean-dark-ui-theme, v1.5.1
base16-ocean-dark-spacegray, v0.12.0
build, v0.46.0

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Probably same issue as #181 . Just close and restart the Atom editor. Possibly re-install `build`.

**Comment by photex** [comment]
I've tried this several ways over and I still get this each time atom opens. Anything I can do to help you triage?

**Comment by noseglid** [comment]
Hmm.. for some reason `atom.project.getPaths()` seems to return `/atom:`. How do you start Atom? What is in the root of the opened project?

Could you try re-install Atom?

**Comment by photex** [comment]
I have several "project folders" open, one in particular is my .atom settings folder since I'm configuring keybindings and so on while getting started with atom.

**Comment by noseglid** [comment]
What if you close, and re-open each project root folder one at a time, and reload atom after each to try and pin-point which root folder is causing it.

**Comment by photex** [comment]
I'm unable to reproduce this error again and I've seen the following behaviors:

- new window with the settings folder as the only project folder. I get the warning that there isn't a build configured for the project.
- new window with an actual project folder. I'm able to use the builder.
- A window opened as mentioned before with multiple project folders opened. I now get the correct warning about a builder not being determined.

So... I guess this can be chalked up to gremlins in atom :clap:

**Comment by noseglid** [comment]
I'll close this out then. Thanks for taking the time to debug it with me.

**Comment by photex** [comment]
Cheers!

**Comment by idleberg** [comment]
I'm getting the same error on two versions of Mac OS X (10.9 and 10.11) when pressing the keyboard shortcut, but it works perfectly on Windows 10.

```
ATOM_SHELL_ASAR.js:0
Error: ENOENT: no such file or directory, lstat '/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /Users/me/.atom/packages/build/lib/build.js:127:27
    at Array.find (native)
    at Object.activePath (/Users/me/.atom/packages/build/lib/build.js:126:74)
    at Object.updateStatusBar (/Users/me/.atom/packages/build/lib/build.js:133:49)
    at /Users/me/.atom/packages/build/lib/build.js:68:57
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:327:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```

**Atom version**: 1.5.3
**build version**: 0.55.0

If there's anything I can do to help debugging, let me know. I can test this on Fedora later when I get home.
