### ISSUE TITLE
Cannot find module 'once'

### ISSUE THREAD

**Issue by abduelhamit** [noseglid/atom-build#193]
1. Update Atom
2. Update build

**Atom Version**: 1.0.19
**System**: MRYEAH-PC
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.47.0

### Stack Trace

Failed to load the build package

```
At Cannot find module 'once'

Error: Cannot find module 'once'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Abdülhamit\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\index.js:4:12)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Abdülhamit\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
altgr, v0.1.0
build, v0.47.0
file-icons, v1.6.9
go-plus, v3.5.1
keyboard-localization, v1.4.8
symbols-tree-view, v0.10.0

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Seems as all dependecies weren't correctly installed. Try to uninstall and re-install `build`.

**Comment by abduelhamit** [comment]
I completely reinstalled Atom (including cleanup). It didn't help.

**Comment by noseglid** [comment]
Could you issue these commands in a command prompt and paste the output:
```
apm uninstall build
apm install build
```

also, could you tell me the content of `C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\node_modules` ?

**Comment by abduelhamit** [comment]
```
C:\Users\Abdülhamit\AppData\Local\atom\bin>dir C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\node_modules
 Datenträger in Laufwerk C: ist Windows und Programme
 Volumeseriennummer: D283-5CF7

 Verzeichnis von C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\node_modules

28.09.2015  15:06    <DIR>          .
28.09.2015  15:06    <DIR>          ..
28.09.2015  15:06    <DIR>          once
               0 Datei(en),              0 Bytes
               3 Verzeichnis(se), 22.341.496.832 Bytes frei

C:\Users\Abdülhamit\AppData\Local\atom\bin>dir C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\node_modules\once
 Datenträger in Laufwerk C: ist Windows und Programme
 Volumeseriennummer: D283-5CF7

 Verzeichnis von C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\node_modules\once

28.09.2015  15:06    <DIR>          .
28.09.2015  15:06    <DIR>          ..
28.09.2015  15:06             1.310 LICENSE
28.09.2015  15:06               346 once.js
28.09.2015  15:06             1.057 package.json
28.09.2015  15:06               549 README.md
28.09.2015  15:06    <DIR>          test
               4 Datei(en),          3.262 Bytes
               3 Verzeichnis(se), 22.340.968.448 Bytes frei

C:\Users\Abdülhamit\AppData\Local\atom\bin>apm uninstall build
Uninstalling build done
C:\Users\Abdülhamit\AppData\Local\atom\bin>apm install build
Installing build to C:\Users\Abdulhamit\.atom\packages done
C:\Users\Abdülhamit\AppData\Local\atom\bin>dir C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\node_modules
 Datenträger in Laufwerk C: ist Windows und Programme
 Volumeseriennummer: D283-5CF7

 Verzeichnis von C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\node_modules

02.10.2015  19:31    <DIR>          .
02.10.2015  19:31    <DIR>          ..
02.10.2015  19:32    <DIR>          once
               0 Datei(en),              0 Bytes
               3 Verzeichnis(se), 22.322.929.664 Bytes frei

C:\Users\Abdülhamit\AppData\Local\atom\bin>dir C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\node_modules\once
 Datenträger in Laufwerk C: ist Windows und Programme
 Volumeseriennummer: D283-5CF7

 Verzeichnis von C:\Users\Abdülhamit\.atom\packages\build\node_modules\tree-kill\node_modules\once

02.10.2015  19:32    <DIR>          .
02.10.2015  19:32    <DIR>          ..
02.10.2015  19:31             1.310 LICENSE
02.10.2015  19:31               346 once.js
02.10.2015  19:31             1.228 package.json
02.10.2015  19:31               549 README.md
02.10.2015  19:32    <DIR>          test
               4 Datei(en),          3.433 Bytes
               3 Verzeichnis(se), 22.322.929.664 Bytes frei
```

Don't mind that it's sometimes Abd**ü**lhamit and sometimes Abd**u**lhamit. It's the result of a long history of non-ASCII char errors. They both lead to the same directory.

**Comment by noseglid** [comment]
I don't think this has anything to do with the `build` package. After all, `tree-kill` is just a depepndency, which has another dependency `once`. For some reason these are not required correctly when activating `build`. It is really `Atom` (or really, `nodejs`) handling the requires. I suggest you open an issue at atom/atom.

**Comment by abduelhamit** [comment]
Thanks for your help. I finally fixed it.

It was a motherfucking non-ASCII char error again. For some reason, it tried to access the `package.json` of `once`, and only that, in `C:\Users\Abdﾃｼlhamit` instead of `C:\Users\Abdülhamit`.

The fix was easy:

    C:\Users>mklink /J Abdﾃｼlhamit Abdülhamit

**Comment by noseglid** [comment]
I'm glad it worked out.
