### ISSUE TITLE
Error when attempting custom build

### ISSUE THREAD

**Issue by tgouhier** [noseglid/atom-build#195]
I'm getting the following error every time I initiate a custom build:
```
ENOENT: no such file or directory, lstat '/atom:'
Error: ENOENT: no such file or directory, lstat '/atom:'
  at Error (native)
  at fs.lstatSync (fs.js:844:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
  at Object.realpathSync (fs.js:1449:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
  at /Users/USERNAME/.atom/packages/build/lib/build.js:170:27
  at baseFindIndex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:326:11)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3241:23)
  at Object.activePath (/Users/USERNAME/.atom/packages/build/lib/build.js:169:16)
  at Object.refreshTargets (/Users/USERNAME/.atom/packages/build/lib/build.js:187:21)
  at Object.<anonymous> (/Users/USERNAME/.atom/packages/build/lib/build.js:309:54)
  at process._tickCallback (node.js:365:9)
```
The contents of my build file (.atom-build.json) are:
```
{
  "cmd": "/Users/USERNAME/render.sh",
  "name": "{FILE_ACTIVE}",
  "args": [ "rhand", "rpres", "clean" ],
  "sh": true,
  "cwd": "{FILE_ACTIVE_PATH}"
  "env": {
  },
    "errorMatch": [
  ],
    "keymap": "",
    "targets": {
    }
}
```

**Comment by noseglid** [comment]
Which version of `build` are you using?

**Comment by tgouhier** [comment]
The problem only occurred in an older version of build. The custom build works fine under the current version of build, thanks!
