### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cancel' of undefined

### ISSUE THREAD

**Issue by artemad** [noseglid/atom-build#202]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.47.0

### Stack Trace

Uncaught TypeError: Cannot read property 'cancel' of undefined

```
At /Users/artemadams/.atom/packages/build/lib/build.js:119

TypeError: Cannot read property 'cancel' of undefined
  at Object.<anonymous> (/Users/artemadams/.atom/packages/build/lib/build.js:121:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  4x -0:25.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:20.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.9.0 build:toggle-panel (button.btn.btn-default.icon.icon-link-external)
     -0:14.1.0 build:trigger (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-atom-material-ui)
     -0:10.3.0 command-palette:toggle (div.settings-view.pane-item)
  3x -0:08.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  3x -0:06.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 build:error-match (div.settings-view.pane-item)
     -0:04.8.0 command-palette:toggle (div.settings-view.pane-item)
  4x -0:02.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.0 build:no-confirm (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "japanese-menu",
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs, v0.3.0
angularjs-snippets, v0.10.18
atom-beautify, v0.28.14
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.2
atom-terminal, v0.8.0
atom-ternjs, v0.8.2
atom-typescript, v7.4.0
build, v0.47.0
color-picker, v2.0.13
docblockr, v0.7.3
file-icons, v1.6.9
gulp-control, v0.4.3
highlight-selected, v0.10.1
jsformat, v0.9.0
linter, v1.8.1
linter-jshint, v1.2.1
markdown-themeable-pdf, v0.10.0
minimap, v4.13.4
minimap-highlight-selected, v4.3.1
pigments, v0.15.0

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Can you describe what you did to get this?
