### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/run/user/1000/gvfs/sftp:host=192.168.1...

### ISSUE THREAD

**Issue by C-Bouthoorn** [noseglid/atom-build#250]
[Enter steps to reproduce below:]

1. Ctrl - Alt - B

**Atom Version**: 1.3.0-beta5
**System**: Ubuntu 15.10
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.50.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/run/user/1000/gvfs/sftp:host=192.168.1.32,port=2222,user=www-data'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/run/user/1000/gvfs/sftp:host=192.168.1.32,port=2222,user=www-data'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /home/charlie/.atom/packages/build/lib/build.js:172:27
    at Array.find (native)
    at Object.activePath (/home/charlie/.atom/packages/build/lib/build.js:171:74)
    at Object.startNewBuild (/home/charlie/.atom/packages/build/lib/build.js:321:20)
    at /home/charlie/.atom/packages/build/lib/build.js:431:39
    at saveAndContinue (/home/charlie/.atom/packages/build/lib/build.js:438:7)
    at Object.doSaveConfirm (/home/charlie/.atom/packages/build/lib/build.js:442:14)
    at Object.build (/home/charlie/.atom/packages/build/lib/build.js:429:10)
    at atom-workspace.<anonymous> (/home/charlie/.atom/packages/build/lib/build.js:100:69)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:31.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.3.0 build:select-active-target (atom-text-editor.editor.is-focused)
     -0:24.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:02.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.8.0 build:trigger (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "whitespace",
      "wrap-guide",
      "build-defaults"
    ]
  },
  "build": {}
}
```

### Installed Packages

```coffee
# User
build, v0.50.0
build-npm-apm, v0.5.0
color-picker, v2.0.14
language-swift, v0.4.0
language-x86asm, v0.7.1
mac-fix-path, v0.0.0
minimap, v4.16.2

# Dev
No dev packages
```

**Comment by noseglid** [comment]
I have no idea what's going on here.

Do you have any information about that path `/run/user/1000/gvfs/sftp:host=192.168.1.32,port=2222,user=www-data` - seems like some sort of network mount (ftp?).

What are you trying to do when this happens?

**Comment by C-Bouthoorn** [comment]
I'm sorry. The destination was on a network drive, mounted with Nautilus. However, my network went down, so the connection closed. After remounting the connection, everything worked again. The connection was used in a folder which wasn't opened, but atom-build wanted to check it. Not sure if you should add a sort of check if the directory still exists?

**Comment by noseglid** [comment]
Not sure I want to check that every time something is done on the off-chance that the underlaying mount has gone away. The error message is pretty clear about what happened and should be enough for the user to fix it. The `build` plugin won't be able to do anything more than giving a different error message.
