### ISSUE TITLE
0.22.0 update broke my editor

### ISSUE THREAD

**Issue by Nikkelmann** [noseglid/atom-build#28]
```javascript
Error: The ::beforeRemove hook has been replaced by ::detached. See https://github.com/atom/space-pen#attacheddetached-hooks for details.
  at ReleaseNotesStatusBar.View (c:\Users\MyName\.atom\packages\build\node_modules\space-pen\lib\space-pen.js:150:15)
  at new ReleaseNotesStatusBar (c:\Users\MyName\AppData\Local\atom\app-0.165.0\resources\app\node_modules\release-notes\lib\release-notes-status-bar.js:14:58)
  at createStatusEntry (c:\Users\MyName\AppData\Local\atom\app-0.165.0\resources\app\node_modules\release-notes\lib\main.js:63:18)
  at c:\Users\MyName\AppData\Local\atom\app-0.165.0\resources\app\node_modules\release-notes\lib\main.js:70:22
  at Emitter.module.exports.Emitter.emit (c:\Users\MyName\AppData\Local\atom\app-0.165.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.activate (c:\Users\MyName\AppData\Local\atom\app-0.165.0\resources\app\src\package-manager.js:382:27)
  at Atom.module.exports.Atom.startEditorWindow (c:\Users\MyName\AppData\Local\atom\app-0.165.0\resources\app\src\atom.js:605:21)
  at Object.<anonymous> (c:\Users\MyName\AppData\Local\atom\app-0.165.0\resources\app\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (c:\Users\MyName\AppData\Local\atom\app-0.165.0\resources\app\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (c:\Users\MyName\AppData\Local\atom\app-0.165.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///C:/Users/MyName/AppData/Local/atom/app-0.165.0/resources/app/static/index.js:59:25)
```

**Comment by noseglid** [comment]
Hmm, this is really weird. I'm not using either `beforeRemove` or `detached`. If you re-install the build package, will it work then?

**Comment by abduelhamit** [comment]
I have the exact same issue. I looked up and it is `space-pen 4.3.3`, the current version.
Looks more like the new version makes some trouble.

**Comment by abduelhamit** [comment]
I looked it up. The cause of this issue is `release-notes` from Atom itself. It's build against `space-pen 4.3.0`, which is incompatible to `>=4.3.1`.

So here's a temporarily fix:
Delete `\.atom\packages\build\node_modules\space-pen` and replace it with a copy from `\AppData\Local\atom\app-0.165.0\resources\app\node_modules\release-notes\node_modules\space-pen`.
Then go to `\.atom\packages\build\package.json` and replace

        "name": "space-pen",
        "version": "4.3.3",

with

        "name": "space-pen",
        "version": "4.3.0",

**Comment by noseglid** [comment]
It appears as we should not require `space-pen`, but rather `atom-space-pen-views` [as described in this post](https://github.com/atom/atom/blob/da46c80db1c4d4ccbf1c7c35efc1fb8b666ccdd7/docs/upgrading/upgrading-your-package.md).

I'm still not sure why this problem only affects some users... could anyone of you guys who had the issue see if `v0.22.1` works without any issues?

**Comment by abduelhamit** [comment]
Now I have `v0.22.4` installed. I didn't test Build itself but this issue is gone.
