### ISSUE TITLE
Failed to load package named 'build' TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by sryze** [noseglid/atom-build#29]
Error after Atom startup:

```
Failed to load package named 'build' TypeError: Cannot read property 'prototype' of undefined
  at Object.module.exports.extends (/home/szx/.atom/packages/build/lib/cscompatability.js:16:26)
  at /home/szx/.atom/packages/build/lib/save-confirm-view.js:11:26
  at Object.<anonymous> (/home/szx/.atom/packages/build/lib/save-confirm-view.js:67:3)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/szx/.atom/packages/build/lib/build.js:9:23)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:602:34)
  at /usr/share/atom/resources/app/src/package.js:180:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:157:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:171:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:339:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:316:14)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:602:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:59:25)
```

Atom version: 0.166.0
atom-build version: 0.22.1

**Comment by noseglid** [comment]
What OS are you on?

**Comment by sryze** [comment]
Now there's another error:

```
TypeError: Cannot read property 'prototype' of undefined
  at __extends (/usr/share/atom/resources/app/node_modules/image-view/lib/image-editor-status-view.js:4:199)
  at /usr/share/atom/resources/app/node_modules/image-view/lib/image-editor-status-view.js:13:5
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/image-view/lib/image-editor-status-view.js:84:5)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/image-view/lib/image-editor-status-view.js:86:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at createImageStatusView (/usr/share/atom/resources/app/node_modules/image-view/lib/main.js:28:31)
  at /usr/share/atom/resources/app/node_modules/image-view/lib/main.js:16:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:383:27)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:605:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:59:25)
```

Actually I think it was there before, I just copy the whole output (sorry). If I remove build with apm everything works fine.

I'm using Ubuntu 14.04.

**Comment by noseglid** [comment]
I'm trying to find the source of this (https://discuss.atom.io/t/requiring-atom-space-pen-views-give-me-a-filter-function/14101)

It appears to have something to do with when I'm requiring space-pen (or atom-space-pen-views). I'm able to reproduce what you're seeing. I'll keep digging...

**Comment by sryze** [comment]
If I run Atom in dev mode the error does not occur. I installed build with `apm link --dev`. I don't know why as both seem to be the same version.

Could some other package trigger this?

**Comment by noseglid** [comment]
I'm not sure.

When I have build enabled (also on Ubuntu 14.04, on OSX it works fine) i get the same errors. If I disable it, everything seems to work.

At two places in the code I do `var View = require('atom-space-pen-views`).View`. If I remove those everything runs. So it is as if atom-build is corrupting the require cache. Altough I'm not sure how.

**Comment by sryze** [comment]
```
/home/szx/.atom/dev/packages (1)
└── build@0.22.3

/home/szx/.atom/packages (7)
├── auto-detect-indentation@0.3.0
├── build@0.22.3
├── indentation-indicator@0.3.0
├── language-cmake@0.1.1
├── minimap@3.5.3
├── open-recent@2.0.0
└── sublime-tabs@0.4.8
```

**Comment by nathancarter** [comment]
I'm also getting [sryze's second error message](https://github.com/noseglid/atom-build/issues/29#issuecomment-69036475) on startup, but on OSX Yosemite, with the latest Atom.  I went through my config and enabled/disabled packages individually.  The error appears if and only if the `build` package is enabled.

**Comment by noseglid** [comment]
Update: This seems to be an issue with the module loader. For some reason, when atom-build require's 'atom-space-pen-views' to build the graphical elements, it doesn't return that.

It seems to only be a problem when it is installed "the normal way". A quick work around right now until I get a response from the dev-team is to clone atom-build somewhere and link it manually

```
git clone https://github.com/noseglid/atom-build
cd atom-build
apm install
apm link
```

For some reason, the issue with the module loader doesn't seem to be affected in this case (at least for me).

**Comment by noseglid** [comment]
Please upgrade to `0.22.4` and everything should work again. If you're still having problems, please get back!

Thanks for reporting this!

**Comment by nathancarter** [comment]
Yup, that fixes it for me -- thank you!

**Comment by sryze** [comment]
Yeah, for me it works too. Thanks.
