### ISSUE TITLE
Uncaught TypeError: this.tooltip.dispose is not a function

### ISSUE THREAD

**Issue by laughedelic** [noseglid/atom-build#313]
I just installed the package and this error popped-up.

**Atom Version**: 1.5.0-beta3
**System**: Mac OS X 10.11.1
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.54.1

### Stack Trace

Uncaught TypeError: this.tooltip.dispose is not a function

```
At /Users/laughedelic/.atom/packages/build/lib/status-bar-view.js:38

TypeError: this.tooltip.dispose is not a function
    at StatusBarView.destroy (/Users/laughedelic/.atom/packages/build/lib/status-bar-view.js:38:20)
    at StatusBarView.attach (/Users/laughedelic/.atom/packages/build/lib/status-bar-view.js:14:10)
    at /Users/laughedelic/.atom/packages/build/lib/status-bar-view.js:9:55
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:141:21)
    at new StatusBarView (/Users/laughedelic/.atom/packages/build/lib/status-bar-view.js:9:17)
    at Object.consumeStatusBar (/Users/laughedelic/.atom/packages/build/lib/build.js:501:26)
    at Provider.module.exports.Provider.provide (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -3:51.2.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:51.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-native-ui)
  7x -3:51.2.0 blur (atom-text-editor.editor.vim-mode.normal-mode)
     -2:22.2.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -2:22.2.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:22.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-native-ui)
 10x -2:22.2.0 blur (div.package-detail.panels-item)
     -2:18.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -2:14.8.0 blur (atom-text-editor.editor.mini.is-focused)
     -1:37.7.0 core:move-to-top (div.panels)
     -1:35.8.0 blur (div.panels)
     -1:35 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -1:33.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -1:30.8.0 blur (atom-text-editor.editor.mini.is-focused)
     -1:28.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  9x -1:22.7.0 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "keybinding-resolver",
      "language-objective-c",
      "distraction-free-mode",
      "language-gfm",
      "autocomplete",
      "markdown-writer",
      "markdown-lists",
      "markmon-preview",
      "markdown-preview",
      "remember-session",
      "mechanical-keyboard",
      "autocomplete-css",
      "git-tab-status",
      "minimap-git-diff",
      "autocomplete-atom-api",
      "language-clojure",
      "language-html",
      "language-javascript",
      "language-less",
      "language-ruby",
      "language-c",
      "language-csharp",
      "language-go",
      "language-make",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby-on-rails",
      "language-sass",
      "language-sql",
      "language-toml",
      "language-xml",
      "scala-worksheet",
      "scala-worksheet",
      "autocomplete-snippets",
      "autocomplete-html",
      "move-status-items",
      "autocomplete-emojis",
      "welcome",
      "autocomplete-paths",
      "bookmarks",
      "background-tips",
      "encoding-selector",
      "archive-view",
      "markdown-mindmap",
      "autocomplete-bibtex",
      "package-switch",
      "language-idris",
      "antialiased",
      "vim-mode-plus",
      "auto-reveal-in-sidebar",
      "active-files",
      "line-ending-selector",
      "hyperclick",
      "linter-manager",
      "linter-annotations",
      "semanticolor",
      "pull-requests",
      "atom-telegram",
      "nav-panel",
      "metrics",
      "linter-markdown",
      "linter-scalac",
      "Ensime",
      "imdone-atom",
      "imdone-atom-github",
      "todo-manager",
      "bottom-dock",
      "git-travel",
      "git-plus",
      "git-diff"
    ],
    "projectHome": "~/dev",
    "themes": [
      "native-ui",
      "atom-material-syntax"
    ]
  },
  "build": {
    "saveOnBuild": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.14.1
atom-material-syntax, v0.3.2
auto-reveal-active-file, v0.3.1
autoflow-diffable, v0.5.0
build, v0.54.1
cursor-history, v0.5.9
file-icons, v1.6.14
github-notifications, v0.1.2
highlight-selected, v0.11.2
language-diff, v0.4.0
language-elm, v1.3.2
language-haskell, v1.5.2
language-latex, v0.6.1
language-pfm, v0.82.0
language-scala, v1.1.6
latex-completions, v0.3.1
line-diff-details, v1.2.0
linter, v1.11.3
markdown-preview-plus, v2.2.2
markdown-scroll-sync, v2.0.3
markdown-table-formatter, v2.7.2
mathjax-wrapper, v0.1.0
minimap, v4.19.0
minimap-codeglance, v0.4.5
native-ui, v0.16.1
package-manager-commands, v2.0.3
pdf-view, v0.39.0
plain-simple, v1.0.3
pretty-json, v0.4.1
project-folder, v0.1.8
swackets, v0.10.0
vim-mode, v0.64.0
yuno-commit, v0.3.1

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Does this happen continually or just this once?

**Comment by laughedelic** [comment]
It appeared just right after installation. I didn't see it since then.

**Comment by noseglid** [comment]
Haven't seen this before. I will close this as a one-off. If this happens again or you find steps to reproduce, please re open the ticket. Thanks for the report.

**Comment by yuchi** [comment]
I encountered this issue again today on `1.5.4`.
