### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Volumes/home'

### ISSUE THREAD

**Issue by peterloron** [noseglid/atom-build#322]
The build plugin throws exceptions when a file is open in the editor and the volume the file is on is no longer present (e.g. network share). The plugin should handle this case gracefully and allow the file to be closed (alert for possible lost work) or saved to an alternate place.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.54.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Volumes/home'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Volumes/home'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /Users/peterl/.atom/packages/build/lib/build.js:127:27
    at Array.find (native)
    at Object.activePath (/Users/peterl/.atom/packages/build/lib/build.js:126:74)
    at Object.updateStatusBar (/Users/peterl/.atom/packages/build/lib/build.js:133:49)
    at /Users/peterl/.atom/packages/build/lib/build.js:68:57
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:312:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:402:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:464:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/peterl/Projects"
  },
  "build": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.19
atom-html-preview, v0.1.13
autocomplete-clang, v0.8.9
autocomplete-python, v1.6.1
build, v0.54.1
fonts, v1.1.0
language-ansible, v0.1.3
language-chef, v0.8.0
language-docker, v1.1.6
language-groovy, v0.5.0
language-ini, v1.14.0
linter, v1.11.3
linter-foodcritic, v0.5.2
linter-gcc, v0.6.5
linter-python-pep8, v0.2.0
remote-edit, v1.8.24
seti-icons, v0.4.5
sync-settings, v0.6.0
terminal-plus, v0.14.5
tool-bar, v0.2.0

# Dev
No dev packages
```

**Comment by C-Bouthoorn** [comment]
Also related to https://github.com/noseglid/atom-build/issues/250 (I remembered having this problem before too)

**Comment by kurzkopfgleitbeutler** [comment]
For me it can't be that the volume the file is on not being present anymore, since the file is still definitely there and the volume it resides in is my whole system.

[Enter steps to reproduce below:]

1. opened file javascript.js with the following contents:
```include node.js;

function bla (A) {
  A = 5;
  return A;
}

```

**Atom Version**: 1.5.3
**System**: linux 4.4.1-2-ARCH
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.55.0


### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/foo/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/foo/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /home/foo/.atom/packages/build/lib/build.js:127:27
    at Array.find (native)
    at Object.activePath (/home/foo/.atom/packages/build/lib/build.js:126:74)
    at Object.updateStatusBar (/home/foo/.atom/packages/build/lib/build.js:133:49)
    at /home/foo/.atom/packages/build/lib/build.js:68:57
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app.asar/src/pane.js:312:19)
    at Pane.module.exports.Pane.activateNextItem (/usr/share/atom/resources/app.asar/src/pane.js:267:21)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:400:16)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:464:16)
    at atom-tabs.TabBarView.onClick (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "build": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.21.0
build, v0.55.0
build-gulp, v0.7.0
build-make, v0.7.0
highlight-selected, v0.11.2
language-lua, v0.9.4
language-pfm, v0.82.0
minimap, v4.19.0
pigments, v0.24.1
terminal-plus, v0.14.5

# Dev
No dev packages
```
