### ISSUE TITLE
If project directory is removed on closing file build causes exception

### ISSUE THREAD

**Issue by mishak87** [noseglid/atom-build#323]
**Atom Version**: 1.5.3
**System**: Ubuntu 15.10
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.54.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/mishak/xxx'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/mishak/xxx'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /home/mishak/.atom/packages/build/lib/build.js:127:27
    at Array.find (native)
    at Object.activePath (/home/mishak/.atom/packages/build/lib/build.js:126:74)
    at Object.updateStatusBar (/home/mishak/.atom/packages/build/lib/build.js:133:49)
    at /home/mishak/.atom/packages/build/lib/build.js:68:57
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app.asar/src/pane.js:312:19)
    at Pane.module.exports.Pane.activatePreviousItem (/usr/share/atom/resources/app.asar/src/pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:402:16)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:464:16)
    at Pane.module.exports.Pane.destroyActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:444:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:657:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/usr/share/atom/resources/app.asar/src/workspace.js:696:21)
    at atom-workspace.commandRegistry.add.core:close (/usr/share/atom/resources/app.asar/src/register-default-commands.js:170:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -9:42.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:41 open-terminal-here:open (span.name.icon.icon-file-text)
 10x -0:07.5.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "highlight-cov",
      "linter-golint",
      "go-find-references",
      "linter-python-pyflakes",
      "linter-phpcs",
      "linter-phpmd",
      "metrics",
      "linter-flake8",
      "linter-jshint",
      "linter-tidy",
      "terminal-plus",
      "xml-formatter"
    ],
    "projectHome": "/home/mishak/workspace/fun",
    "themes": [
      "one-dark-ui",
      "duotone-dark-space-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
apiary-highlighter, v0.4.0
autocomplete-emojis, v2.2.2
build, v0.54.1
build-gulp, v0.7.0
build-make, v0.7.0
build-npm-apm, v0.8.0
compare-files, v0.6.2
devdocs, v0.2.1
docblockr, v0.7.3
duotone-dark-space-syntax, v1.0.0
editorconfig, v1.2.4
environment, v1.1.1
file-icons, v1.6.14
file-types, v0.5.1
git-plus, v5.13.0
git-tab-status, v1.9.2
go-config, v0.3.3
go-plus, v3.5.3
gometalinter-linter, v0.1.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
indentation-indicator, v0.6.0
language-ansible, v0.1.3
language-apache, v1.4.0
language-api-blueprint, v1.0.2
language-crontab, v0.2.1
language-docker, v1.1.6
language-dot, v1.6.0
language-env, v0.1.0
language-hcl, v0.1.2
language-ini, v1.14.0
language-jade, v0.6.3
language-latte, v0.3.1
language-lua, v0.9.4
language-nginx, v0.6.1
language-protobuf, v0.5.0
language-smarty-php, v0.5.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-docker, v0.1.2
linter-eslint, v6.0.0
linter-js-standard, v3.2.1
linter-js-yaml, v1.2.5
linter-jsonlint, v1.1.5
linter-less, v2.4.0
linter-lua, v1.0.1
linter-luacheck, v1.1.4
linter-pep257, v0.4.0
linter-pep8, v1.2.1
linter-php, v1.1.8
linter-pylama, v0.2.6
linter-shellcheck, v1.1.0
linter-xmllint, v1.3.2
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
open-no-binaries, v0.1.0
open-terminal-here, v2.1.4
pigments, v0.24.0
project-manager, v2.7.6
react, v0.14.1
run-in-terminal, v0.6.0
show-repository-web, v0.1.2

# Dev
No dev packages
```

**Comment by C-Bouthoorn** [comment]
Same as https://github.com/noseglid/atom-build/issues/322
