### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/saurav/atom:'

### ISSUE THREAD

**Issue by sauravvarma** [noseglid/atom-build#342]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Ubuntu 15.10
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.56.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/saurav/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/saurav/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /home/saurav/.atom/packages/build/lib/build.js:127:8
    at Array.find (native)
    at Object.activePath (/home/saurav/.atom/packages/build/lib/build.js:126:8)
    at Object.updateStatusBar (/home/saurav/.atom/packages/build/lib/build.js:133:4)
    at /home/saurav/.atom/packages/build/lib/build.js:67:10
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:327:21)
    at atom-tabs.TabBarView.onMouseDown (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```

### Commands

```
  8x -9:33.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -9:32.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:31.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -9:31.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -9:31.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -9:30.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:29.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -9:29.6.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -9:29 core:move-down (atom-text-editor.editor.is-focused)
 10x -9:28 core:move-right (atom-text-editor.editor.is-focused)
  3x -9:11.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:05.3.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -9:04.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -9:03.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:38.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:33.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "build": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
build, v0.56.0
gcc-make-run, v0.2.5
gpp-compiler, v2.0.2
minimap, v4.21.0

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Can you describe what you were doing when this happened? I though I had these issues figured out. In fact, [it's even guarded to catch errors and just return false](https://github.com/noseglid/atom-build/blob/v0.56.0/lib/build.js#L120-L126)!

Can you upgrade to v0.57.0 and see if you can reproduce?

**Comment by noseglid** [comment]
Closing this. Please get back if you still experience the issue after upgrading.
