### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by ichy-wayland** [noseglid/atom-build#347]
So, when i open the program, i get this:

```
/home/dimitri/.atom/packages/build/lib/google-analytics.js:41
Hide Stack Trace
TypeError: Object.assign is not a function
  at /home/dimitri/.atom/packages/build/lib/google-analytics.js:63:16
  at /home/dimitri/.atom/packages/build/lib/google-analytics.js:32:68
  at extractMac (/home/dimitri/.atom/packages/build/node_modules/getmac/out/lib/getmac.js:39:14)
  at /home/dimitri/.atom/packages/build/node_modules/getmac/out/lib/getmac.js:48:16
  at ChildProcess.exithandler (child_process.js:199:7)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:764:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)
```

And when i try to build i get this:
```
/home/dimitri/.atom/packages/build/lib/utils.js:32
Hide Stack Trace
TypeError: atom.project.getPaths(...).sort(...).find is not a function
  at activePath (/home/dimitri/.atom/packages/build/lib/utils.js:52:6)
  at Object.startNewBuild (/home/dimitri/.atom/packages/build/lib/build.js:318:35)
  at /home/dimitri/.atom/packages/build/lib/build.js:472:43
  at saveAndContinue (/home/dimitri/.atom/packages/build/lib/build.js:481:7)
  at Object.doSaveConfirm (/home/dimitri/.atom/packages/build/lib/build.js:485:14)
  at Object.build (/home/dimitri/.atom/packages/build/lib/build.js:470:10)
  at atom-workspace.<anonymous> (/home/dimitri/.atom/packages/build/lib/build.js:94:20)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:240:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)
```

**Comment by noseglid** [comment]
It almost feels like the package wasn't transpiled. Could you re-install the build package and see if that work?

**Comment by ichy-wayland** [comment]
Sorry. My package manager *somehow* missed Atom updates. My local Atom was at 1.0.
So, build dosen't work at 1.0. Sorry for opening an issue that was just outdated Atom.

**Comment by noseglid** [comment]
It does bring a up an important point though. The [specified supported Atom versions](https://github.com/noseglid/atom-build/blob/master/package.json#L9) is obviously incorrect. I'll have that fixed and the next person experiencing this will get a better error message!
