### ISSUE TITLE
Uncaught TypeError: Cannot read property 'loading' of undefined

### ISSUE THREAD

**Issue by noseglid** [noseglid/atom-build#403]
1. Open a project without any build targets
2. Open the select target view

**Atom Version**: 1.8.0-beta2
**System**: Mac OS X 10.11.3
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.60.0

### Stack Trace

Uncaught TypeError: Cannot read property 'loading' of undefined

```
At /Users/noseglid/devel/atom-build/lib/target-manager.js:213

TypeError: Cannot read property 'loading' of undefined
    at TargetManager.isLoading (/Users/noseglid/devel/atom-build/lib/target-manager.js:213:57)
    at TargetManager.selectActiveTarget (/Users/noseglid/devel/atom-build/lib/target-manager.js:174:14)
    at atom-workspace.<anonymous> (/Users/noseglid/devel/atom-build/lib/target-manager.js:23:82)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom-beta/1.7.0-beta4/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom-beta/1.7.0-beta4/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom-beta/1.7.0-beta4/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom-beta/1.7.0-beta4/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/homebrew-cask/Caskroom/atom-beta/1.7.0-beta4/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom-beta/1.7.0-beta4/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:10.8.0 blur (body.platform-darwin.file-icons-tab-pane-icon.trailing-spaces-highlight-indentation)
     -0:10.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:09.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -0:09.8.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:05.9.0 vim-mode:delete-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:05.6.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:05.4.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:05.4.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:05.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:05.2.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 build:trigger (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.1.0 build:select-active-target (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.1.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:00.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:00.0 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "language-hyperlink",
      "link"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "nucleus-dark-ui",
      "oceanic-next"
    ]
  },
  "build": {
    "overrideThemeColors": false,
    "statusBar": "Right"
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.14.0
build, v0.60.0
build-gradle, v0.6.0
build-gulp, v0.8.0
build-npm-apm, v0.10.0
editorconfig, v1.4.0
ex-mode, v0.8.0
file-icons, v1.7.6
highlight-selected, v0.11.2
language-docker, v1.1.6
language-gradle, v0.0.3
language-groovy, v0.6.0
linter, v1.11.4
linter-docker, v0.1.2
linter-eslint, v7.2.1
linter-javac, v1.8.1
minimap, v4.22.1
minimap-git-diff, v4.3.0
minimap-highlight-selected, v4.4.0
nucleus-dark-ui, v0.7.17
oceanic-next, v0.1.2
react, v0.15.0
rest-client, v1.1.0
sync-settings, v0.7.2
trailing-spaces, v0.3.2
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by C-Bouthoorn** [comment]
Interesting. It doesn't error on Atom 1.8.0-beta2 on Linux 4.2.0-36-generic, but displays a nice "No targets found"
