### ISSUE TITLE
Uncaught TypeError: this.getTargets(...).map is not a function

### ISSUE THREAD

**Issue by black-snow** [noseglid/atom-build#420]
1. Hit cmd+alt+t

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.62.0

### Stack Trace

Uncaught TypeError: this.getTargets(...).map is not a function

```
At /Users/xxx/.atom/packages/build/lib/target-manager.js:162

TypeError: this.getTargets(...).map is not a function
    at TargetManager.fillTargets (/Users/xxx/.atom/packages/build/lib/target-manager.js:162:47)
    at TargetManager.selectActiveTarget (/Users/xxx/.atom/packages/build/lib/target-manager.js:185:12)
    at atom-workspace.<anonymous> (/Users/xxx/.atom/packages/build/lib/target-manager.js:23:82)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -4:43.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -3:53.6.0 build:toggle-panel (div.panels-item)
     -3:51.2.0 core:paste (div.panels-item)
     -0:01.6.0 build:select-active-target (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/xxx"
  }
}
```

### Installed Packages

```coffee
# User
build, v0.62.0
build-rake, v0.1.1
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.11
goto-definition, v1.1.15
highlight-selected, v0.11.2
linter, v1.11.4
linter-ruby, v1.2.2
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-pigments, v0.2.1
pigments, v0.26.2
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by black-snow** [comment]
Can't run any rake task anymore except `about`. Hitting any other task will also run `about`. Dunno whether this is an issue with build or w/ build-rake.

**Comment by noseglid** [comment]
I am unable to reproduce this.
![rake](https://cloud.githubusercontent.com/assets/933880/15257871/c99c58fc-1948-11e6-99cf-fda373ec90e3.gif)

However, examining the stack trace I found one issue which might be the culprit. If you have the chance, please give #420 a test.

**Comment by black-snow** [comment]
It's fixed now, thanks.

**Comment by noseglid** [comment]
👍

**Comment by black-snow** [comment]
After updating build I got this error again :{

> [Enter steps to reproduce below:]

1. update to latest build version
2. hit cmd+alt+t

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.64.0


### Stack Trace

Uncaught TypeError: this.getTargets(...).map is not a function

```
At /Users/xxx/.atom/packages/build/lib/target-manager.js:160

TypeError: this.getTargets(...).map is not a function
    at TargetManager.fillTargets (/Users/xxx/.atom/packages/build/lib/target-manager.js:160:21)
    at TargetManager.selectActiveTarget (/Users/xxx/.atom/packages/build/lib/target-manager.js:180:12)
    at atom-workspace.<anonymous> (/Users/xxx/.atom/packages/build/lib/target-manager.js:23:82)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:17.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:29.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:15.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:12.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.8.0 git-plus:pull (atom-text-editor.editor)
     -0:01.2.0 build:select-active-target (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "ruby-test"
    ],
    "projectHome": "/Users/xxx"
  }
}
```

### Installed Packages

```coffee
# User
build, v0.64.0
build-rake, v0.1.1
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.13
git-plus, v5.14.0
goto-definition, v1.1.16
highlight-selected, v0.11.2
hyperclick, v0.0.36
hyperlink-hyperclick, v1.3.3
linter, v1.11.4
linter-ruby, v1.2.2
merge-conflicts, v1.4.3
minimap, v4.24.3
minimap-pigments, v0.2.1
pigments, v0.29.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by black-snow** [comment]
After an atom restart a pop-up popped up: "Installed build dependencies" "Installed busy".
Now build is working again.
