### ISSUE TITLE
Uncaught TypeError: Cannot set property 'loading' of undefined

### ISSUE THREAD

**Issue by TitanNano** [noseglid/atom-build#435]
[Enter steps to reproduce below:]

1. switch project with project ring, there is no build target present in the new project

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.64.0

### Stack Trace

Uncaught TypeError: Cannot set property 'loading' of undefined

```
At /Users/Jovan/.atom/packages/build/lib/target-manager.js:60

TypeError: Cannot set property 'loading' of undefined
    at /Users/Jovan/.atom/packages/build/lib/target-manager.js:60:25
    at Array.map (native)
    at TargetManager.refreshTargets (/Users/Jovan/.atom/packages/build/lib/target-manager.js:58:39)
    at emitNone (events.js:67:13)
    at GulpBuildProvider.emit (events.js:166:7)
    at FSWatcher.<anonymous> (/Users/Jovan/.atom/packages/build-gulp/lib/gulp.js:69:55)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1310:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "project-ring"
    ]
  },
  "build": {
    "buildOnSave": true,
    "panelVisibility": "Show on Error",
    "saveOnBuild": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
atom-import-js, v0.2.2
atom-ternjs, v0.14.1
auto-indent, v0.5.0
build, v0.64.0
build-cargo, v0.15.0
build-grunt, v0.4.0
build-gulp, v0.9.0
busy, v0.5.0
color-picker, v2.1.1
css-color-underline, v1.0.1
docs-snippets, v0.8.0
emmet, v2.4.3
file-type-icons, v1.3.0
language-rust, v0.4.6
linter, v1.11.4
linter-csslint, v1.3.2
linter-eslint, v7.2.2
linter-jshint, v2.1.0
linter-jsonlint, v1.2.5
linter-perl, v0.8.0
linter-php, v1.2.0
linter-rust, v0.4.6
linter-sass-lint, v1.5.0
merge-conflicts, v1.4.3
project-ring, v0.38.1
racer, v0.20.0
travis-ci-status, v1.1.1

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Did you restart atom after upgrading? Is this consistent?

**Comment by TitanNano** [comment]
I restarted atom a couple of times, but after I tested it again just now, it worked just fine. Thank you anyway 👍
