### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sh' of undefined

### ISSUE THREAD

**Issue by rosterloh** [noseglid/atom-build#45]
Basic build file:

{
  "cmd": "echo",
  "args": "{ACTIVE_FILE}"
}

**Atom Version**: 0.184.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.24.0

### Stack Trace

Uncaught TypeError: Cannot read property 'sh' of undefined

```
At C:\Users\richard.osterloh\.atom\packages\build\lib\build.js:245

TypeError: Cannot read property 'sh' of undefined
  at ChildProcess.<anonymous> (C:\Users\richard.osterloh\.atom\packages\build\lib\build.js:245:38)
  at ChildProcess.emit (events.js:116:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1070:12)
  at child_process.js:1142:20
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -7:52.7 build:trigger (atom-text-editor.editor)
     -7:36.9 window:run-package-specs (atom-text-editor.editor)
     -7:24.7 core:backspace (atom-text-editor.editor)
     -7:22.2 command-palette:toggle (atom-text-editor.editor)
  2x -7:20.1 core:move-down (atom-text-editor.editor.mini)
  2x -7:18.7 core:move-up (atom-text-editor.editor.mini)
     -7:18.0 core:confirm (atom-text-editor.editor.mini)
     -7:18.0 build:stop (atom-text-editor.editor)
     -0:35.0 core:delete (atom-text-editor.editor)
     -0:26.0 core:paste (atom-text-editor.editor)
     -0:22.6 core:save (atom-text-editor.editor)
     -0:19.5 build:trigger (atom-text-editor.editor)
     -0:11.7 command-palette:toggle (atom-text-editor.editor)
     -0:09.1 core:confirm (atom-text-editor.editor.mini)
     -0:09.1 build:stop (atom-text-editor.editor)
     -0:05.7 build:trigger (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-clang",
      "symbols-view"
    ]
  },
  "build": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-ctags, v2.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.0
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v1.0.1
build, v0.24.0
color-picker, v1.4.4
jsdoc, v0.9.0
language-cmake, v0.1.1
language-docker, v1.1.2
linter, v0.12.0
linter-cpplint, v0.1.3
linter-javac, v0.1.3
linter-jshint, v0.1.0
linter-scss-lint, v0.0.14
minimap, v4.5.0
symbols-tree-view, v0.6.1
sync-settings, v0.2.1

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Thanks for the report. I will submit a patch release shortly where this is should be fixed.
