### ISSUE TITLE
Error when using with flex-tool-bar

### ISSUE THREAD

**Issue by Jndachenhaus** [noseglid/atom-build#462]
Using callback build:trigger gives an error.
Uncaught TypeError: Cannot read property 'startsWith' of undefined

If anyone knows how to fix this it'd be much appreciated

**Comment by noseglid** [comment]
Any stack trace to this?

**Comment by Jndachenhaus** [comment]
TypeError: Cannot read property 'startsWith' of undefined
    at toolBar.addButton.callback (/home/jndachenhaus/.atom/packages/flex-tool-bar/types/url.coffee:10:13)
    at executeCallback (/home/jndachenhaus/.atom/packages/tool-bar/lib/tool-bar-button-view.js:107:5)
    at ToolBarButtonView._onClick (/home/jndachenhaus/.atom/packages/tool-bar/lib/tool-bar-button-view.js:69:7)

**Comment by Jndachenhaus** [comment]
This was my bad, misspelled something and didn't notice it until looking it over for the seventh time
