### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by Etholiase** [noseglid/atom-build#507]
[Enter steps to reproduce:]

1. I was on Atom when this error appeared
2. I didn't do special things (i was just building python scripts)

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [build](https://github.com/noseglid/atom-build) package 0.67.0

### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Users/David/.atom/packages/build/lib/build.js:168

RangeError: Invalid string length
    at /packages/build/lib/build.js:168:36)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -2:53.5.0 core:save (input.hidden-input)
  2x -2:52.7.0 build:trigger (input.hidden-input)
  2x -2:30.7.0 core:backspace (input.hidden-input)
     -2:26.7.0 core:move-right (input.hidden-input)
  4x -2:25.7.0 core:backspace (input.hidden-input)
     -2:20.9.0 core:save (input.hidden-input)
     -2:20.1.0 build:trigger (input.hidden-input)
     -1:55.3.0 autocomplete-plus:confirm (input.hidden-input)
     -1:53.1.0 core:save (input.hidden-input)
  2x -1:52.4.0 build:trigger (input.hidden-input)
     -1:36.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:34.9.0 core:move-right (input.hidden-input)
     -1:32.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -1:31.4.0 core:move-right (input.hidden-input)
  2x -1:30.3.0 core:save (input.hidden-input)
  2x -1:22.5.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.6 
atomify 0.3.0 
autocomplete-python 1.8.63 
build 0.67.0 
build-python 0.9.1 
busy 0.7.0 
```

**Comment by noseglid** [comment]
Does this error happen frequently or have you seen it just once?

**Comment by Etholiase** [comment]
Frequently :/ (30 minutes)

**Comment by noseglid** [comment]
Looks like you're getting non-strings from a build command. Could you provide the build configuration you use?
