### ISSUE TITLE
Uncaught TypeError: Cannot read property 'deleteMessages' of undefined

### ISSUE THREAD

**Issue by EugeneTelyatnik** [noseglid/atom-build#508]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [build](https://github.com/noseglid/atom-build) package 0.67.0

### Stack Trace

Uncaught TypeError: Cannot read property 'deleteMessages' of undefined

```
At /Users/eugene/.atom/packages/build/lib/linter-integration.js:11

TypeError: Cannot read property 'deleteMessages' of undefined
    at Linter.clear (/packages/build/lib/linter-integration.js:11:16)
    at Object.startNewBuild (/packages/build/lib/build.js:109:32)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:64:62)
    at emitOne (events.js:96:13)
    at TargetManager.emit (events.js:188:7)
    at /packages/build/lib/target-manager.js:113:125)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at Object.runAtomCommand (/packages/platformio-ide/lib/utils.js:250:24)
    at /packages/platformio-ide/lib/main.js:194:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:106:19)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:70:7)
```

### Commands

```
     -5:41 tree-view:add-file (span.name.icon.icon-file-directory)
     -5:31.8.0 core:backspace (input.hidden-input)
     -5:30.7.0 core:confirm (input.hidden-input)
     -5:07.0 core:paste (input.hidden-input)
     -5:03.9.0 core:save (input.hidden-input)
     -5:02.0 platformio-ide:target:build (input.hidden-input)
     -5:02.0 platformio-ide:target:build-/Users/eugene/Code/iot/esp8266 test (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:37.5.0 platformio-ide:target:build (input.hidden-input)
     -4:37.5.0 platformio-ide:target:build-/Users/eugene/Code/iot/esp8266 test (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:34.1.0 core:save (input.hidden-input)
     -4:19.2.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -4:17.6.0 editor:consolidate-selections (input.hidden-input)
     -4:17.6.0 core:cancel (input.hidden-input)
     -0:13.2.0 platformio-ide:target:build (input.hidden-input)
     -0:13.2.0 platformio-ide:target:build-/Users/eugene/Code/iot/esp8266 test (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.10.1 
build 0.67.0 
busy 0.7.0 
file-icons 2.1.3 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.3 
linter-gcc 0.7.1 
linter-ui-default 1.2.3 
minimap 4.27.1 
platformio-ide 2.0.0-beta.2 
platformio-ide-terminal 2.5.0 
tool-bar 1.1.0 
```

**Comment by MacWyznawca** [comment]
+1

**Comment by cometu** [comment]
at build

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [build](https://github.com/noseglid/atom-build) package 0.67.0


### Stack Trace

Uncaught TypeError: Cannot read property 'deleteMessages' of undefined

```
At /home/come/.atom/packages/build/lib/linter-integration.js:11

TypeError: Cannot read property 'deleteMessages' of undefined
    at Linter.clear (/packages/build/lib/linter-integration.js:11:16)
    at Object.startNewBuild (/packages/build/lib/build.js:109:32)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:25:69)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:28.6.0 command-palette:toggle (input.hidden-input)
  3x -0:28.1.0 core:move-down (input.hidden-input)
  2x -0:27.4.0 core:move-up (input.hidden-input)
     -0:27.1.0 editor:consolidate-selections (input.hidden-input)
     -0:27.1.0 core:cancel (input.hidden-input)
     -0:25.8.0 intentions:highlight (input.hidden-input)
     -0:25.5.0 core:close (input.hidden-input)
     -0:24.8.0 intentions:highlight (input.hidden-input)
     -0:24.7.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:24.6.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:22.9.0 core:close (input.hidden-input)
     -0:22.3.0 intentions:highlight (input.hidden-input)
     -0:22.2.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:22 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:19.3.0 intentions:highlight (input.hidden-input)
     -0:03.1.0 build:trigger (input.hidden-input)
```

### Non-Core Packages

```
atom-cscope 1.0.0 
atom-ctags 5.0.0 
autocomplete-clang 0.10.1 
autocomplete-ctags 0.4.1 
build 0.67.0 
busy 0.7.0 
busy-signal 1.3.0 
ctags-status 1.3.7 
dbg 1.4.1 
dbg-arm-none-eabi-gdb 0.1.5 
dbg-gdb 1.6.2 
ecusim-syntax 0.0.0 
file-icons 2.1.3 
git-blame 1.0.1 
git-plus 7.4.0 
goto-definition 1.3.1 
highlight-selected 0.13.1 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.3 
linter-clang 4.1.1 
linter-cppcheck 0.2.3 
linter-gcc 0.7.1 
linter-ui-default 1.2.3 
minimap 4.27.1 
multi-cursor 2.1.5 
output-panel 0.1.4 
platformio-ide 2.0.0-beta.2 
platformio-ide-terminal 2.4.0 
split-diff 1.3.0 
swd-debugger 0.1.1 
tool-bar 1.1.0 
```

**Comment by Hativ3** [comment]
I think that's a bug in Linter and fixed a hour ago: https://github.com/steelbrain/linter/pull/1434

After updating linter build is working now.

**Comment by noisegate** [comment]
upgraded to [linter v 2.1.4 ](https://github.com/hebaishi/linter-gcc/issues/123) seems to have solved it for me. Ubuntu 16.04LTS

**Comment by noseglid** [comment]
Closing as this was [an issue with linter](https://github.com/steelbrain/linter/pull/1434).
