### ISSUE TITLE
Uncaught Error: Cannot find module '../src/term'

### ISSUE THREAD

**Issue by MrAmazoni** [noseglid/atom-build#522]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [build](https://github.com/noseglid/atom-build) package 0.68.0

### Stack Trace

Uncaught Error: Cannot find module '../src/term'

```
At C:\Users\007\AppData\Local\atom\app-1.17.2\resources\app\static\<embedded>:1

Error: Cannot find module '../src/term'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at Function.Terminal (/packages/build/node_modules/term.js/lib/index.js:48:27)
    at Function.module.exports.TokamakTerminalView.getFocusedTerminal (/packages/tokamak-terminal/lib/view.coffee:122:22)
    at /packages/tokamak-terminal/lib/status-bar.coffee:219:46
```

### Commands

```
     -4:44.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -4:14.5.0 terminal-status:new (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:54.5.0 core:confirm (input.hidden-input)
     -3:45.9.0 terminal-status:toggle (input.hidden-input)
     -3:35.3.0 terminal-panel:new (div.panels-item)
     -2:45.8.0 core:backspace (input.hidden-input)
     -2:41.7.0 core:confirm (input.hidden-input)
     -2:25.5.0 core:backspace (input.hidden-input)
     -2:18.2.0 core:confirm (input.hidden-input)
     -1:26.3.0 core:backspace (input.hidden-input)
     -1:20.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.1.0 
apex-ui 0.2.1 
atom-clock 0.1.8 
atom-commander 0.9.0 
atom-diary 1.2.1 
atom-language-rust 0.12.1 
atom-python-run 0.7.3 
atom-terminal-panel 4.4.4 
autocomplete-bash-builtins 0.3.5 
autocomplete-clang 0.11.3 
autocomplete-computercraft 1.0.0 
autocomplete-java 1.2.7 
autocomplete-lua 0.8.2 
autocomplete-python 1.8.64 
bottom-dock 0.4.4 
build 0.68.0 
build-cmake 0.10.0 
build-cmd 0.5.2 
build-dockerfile 1.0.1 
build-tools 4.5.9 
busy 0.7.0 
busy-signal 1.4.3 
dash 1.7.1 
docker 0.7.0 
file-icons 2.1.7 
file-templates 0.2.0 
gcc-make-run 0.2.9 
git-plus 7.9.3 
github-issues 0.8.3 
github-notifications 0.1.2 
github-utils 1.6.0 
go-debug 1.4.2 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
gpp-compiler 3.0.7 
hey-pane 1.0.0 
Hydrogen 1.16.0 
hyperclick 0.0.40 
intentions 1.1.2 
kite 0.26.0 
language-65asm 5.0.0 
language-armasm 2.0.2 
language-avr-asm 0.3.0 
language-computercraft 0.2.1 
language-cpp14 0.6.2 
language-gmod-lua 0.4.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-lua-wow 0.2.0 
language-minecraft-forge-cfg 0.1.2 
language-rust 0.4.10 
Language-Skript 2.1.3 
language-x86asm 0.9.0 
linter 2.1.4 
linter-coffee-variables 0.6.0 
linter-cppcheck 0.2.3 
linter-cpplint 2.0.1 
linter-gcc 0.7.1 
linter-glualint 0.7.0 
linter-javac 1.9.4 
linter-lua 1.0.4 
linter-luacheck 2.0.1 
linter-luaparse 0.2.0 
linter-manager 0.2.12 
linter-python 3.1.2 
linter-rust 0.8.0 
linter-shellcheck 1.4.4 
linter-ui-default 1.6.0 
linter-write-good 0.9.0 
minimap 4.28.2 
open-bash-git 2.3.3 
open-on-gist 0.1.1 
platformio-aia 0.0.5 
platformio-ide 2.0.0-beta.6 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
python-tools 0.6.9 
racer 0.20.0 
rust-api-docs-helper 0.5.1 
rustfmt 0.1.3 
script 3.15.0 
tabletopsimulator-lua 1.1.7 
tablr 1.8.3 
terminal-panel 1.14.1 
terminal-plus 0.14.5 
terminal-status 1.6.8 
tokamak 0.3.2 
tokamak-terminal 10.0.1 
tool-bar 1.1.0 
vim-mode-plus 0.93.0 
```

**Comment by C-Bouthoorn** [comment]
Was this after an update? If so, could you try restarting Atom?

**Comment by MrAmazoni** [comment]
I have tried restarting but it doesn't help.

**Comment by flakfire** [comment]
Same issue here.

**Comment by noseglid** [comment]
This doesn't seem to have anything with atom-build to do?
The stack trace points to something else (`tokamak-terminal`): `at /packages/tokamak-terminal/lib/status-bar.coffee:219:46`

**Comment by ndugger** [comment]
I got this error after installing the package "PlatformIO"; I'm thinking this isn't tied to atom-build.

**Comment by me21** [comment]
I got this error after trying to upgrade the package "platformio-ide-terminal" to version 2.5.2.

**Comment by noseglid** [comment]
I'll close this as unrelated.
