### ISSUE TITLE
Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by black-snow** [noseglid/atom-build#560]
[Enter steps to reproduce:]

1. I have
2. no idea
3. sorry ...

It seems to happen when also using the platform-io-terminal, I wonder why.
Also my Firefox hangs when I click "report bug" but that sure ain't your fault ;)

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [build](https://github.com/noseglid/atom-build) package 0.70.0

### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /Users/xxx/.atom/packages/build/node_modules/term.js/src/term.js:1939

TypeError: Cannot set property '0' of undefined
    at Terminal.write (/packages/build/node_modules/term.js/src/term.js:1939:55)
    at /packages/platformio-ide-terminal/lib/view.coffee:141:17
    at /Applications/Atom.app/Contents/Resources/app/src/task.js:122:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task.js:74:40)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

### Commands

```
  2x -7:50.5.0 platformio-ide-terminal:copy (div.terminal)
     -6:00.6.0 editor:select-to-beginning-of-word (input.hidden-input)
     -5:59.7.0 intentions:highlight (input.hidden-input)
  2x -5:59.6.0 editor:move-to-beginning-of-word (input.hidden-input)
     -5:56.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -5:55 editor:move-to-first-character-of-line (input.hidden-input)
  7x -5:54.6.0 core:delete (input.hidden-input)
     -5:53.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -5:52.9.0 docblockr:parse-enter (input.hidden-input)
     -5:52.9.0 editor:newline (input.hidden-input)
     -5:51.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
build 0.70.0 
build-gulp 0.11.0 
build-npm-apm 0.12.0 
build-rake 0.1.1 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.13.7 
emmet 2.4.3 
env-from-shell 0.3.0 
file-icons 2.1.18 
git-plus 7.10.2 
git-time-machine 1.5.9 
goto-definition 1.3.4 
highlight-selected 0.13.1 
Hydrogen 2.3.0 
hyperclick 0.1.5 
hyperlink-hyperclick 2.0.0 
intentions 1.1.5 
jsformat 0.9.3 
language-rspec 0.7.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-jsonlint 1.3.0 
linter-ruby 1.2.6 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
node-debugger 1.10.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
prettier-atom 0.52.0 
split-diff 1.5.2 
toggle-quotes 1.1.0 
```

**Comment by black-snow** [comment]
Haha, steps to reproduce:

1. Have `platformio-ide-terminal` installed
2. Have a terminal window open
3. Make it larger per click+drag - everything's fine
4. Make the terminal window smaller per click+drag - error pops up
